[tool.poetry]
name = "free-browser-search-api"
version = "0.1.0"
description = "High-performance Free Browser Search API Gateway"
authors = ["EbxdMalix <https://github.com/EbxdMalix>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10.0,<3.13"
playwright = "1.40.0"
beautifulsoup4 = "*"
markdownify = "*"
uvicorn = "^0.34.0"
fastapi = "^0.115.11"
pydantic = "^2.10.6"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
# https://beta.ruff.rs/docs/configuration/
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"